language: node_js
os:
- linux
- osx
node_js:
- node
- lts/*
before_script:
- yarn global add typescript gts
cache: yarn
before_deploy:
- yarn pack
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: soss-cli-*.tgz
  skip_cleanup: true
  on:
    branch: master
    node: node
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
- provider: npm
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  email: mwei@cs.ucsd.edu
  on:
    tags: true
    node: node
    condition: "$TRAVIS_OS_NAME = linux"
env:
  global:
  - secure: g4xAXjX9/v72/lgjR4eRiObqRA7UxnlMqSp3ypJ+XKIpo64dNiZ+FM8cNAreC1Qp4qMqZOgGdqQzrTtojkDbnLEFQF7a7QCdsoFY0yTd2W7/IQyolL2E8JlbvJXkruSBCI4u1v5cN6BA/1uQy6ZmlUSUq914Pv49R9/27hlR51FFM8devNFHG7nK5un8m3vTXdUmOnThT1BmT9ETKGx8GldpUpIdsNptqOLoPwKCol4Ukds6gJDog4odY1BYHJzXb16MhU3SksbBEgWrctrayFEOnixy0/jKpYRj/Tz4j6XDcJwj73voIzcXTkG+zJjI+3QNTS2mrbRWbuShQ3lT2/iwXv3sNPBmCfNaERYhnnwlMHy66YdiC1aVdE89Y+c4K1VS1M87/tbZbGMqGX/Akm/SfO98G4mBXFEzLndFLGdG9SN1wrgLfwKtHf+vUYuIxZmcws1SZolLxvoIopP+encfaYUenT2lNlzlh1XzqFkbuxAw6uNoVeddImfuwCQErCgqEaM2fbcodu0XfIsSFM8ZF+PiTaiz9d6yxnvpqixesGO1iRp91LChTtLU2fSQqq3GxDztwdeQfryJqEQDPb1X+/YVSut+Fv63VH8Ce5R163Oc+eQlf+GtyeB0PzwtPbufEM9nW8e2siw6D0ZaMYojpVwuxQGAE00awZ8LVnk=
  - secure: kkvGJ5ZaYQevgrrHE5DfUGZvsAt7YevXiF/SMyet64fU6Gpom2ySHf2f/g6WmZSFqJOB3n5qF2+LsnX9ROto0jXRb7jSLyIMwf+pO+otHAj1KcpdfnHnV3WUJj1P9dMtDSKmCE0VbtfzBYSHPO4DbsCfF8TP3FVLdhv0CxIVtmMZhksao7952ubIOyKXcs6PAGuL0IQhew1Q6jyulmxDEdQTfFN7qAHdgweaHdfMlggRK0QWBBsa98/Ixxz/K1lIIhFJux1O97zPKcxK+M8PE2UaNSREKR5kMGVyvWq/Xh7X0ULEnDYpgIidd1SNJFvz5X53hv07zTEKBqfEeIgkE2hmzxM0ER5XHFEqKx15x/Gu1ELhRu1K31q2dNC5A8wYRcPfxE5Ss/8qfKERY1PUexJ4FVGt3JOuo04XdmQz8g44HO+kaEp/BK45S8JlmEFk1AYlFSOktwqKgNbCoWzwKcvV/cVHPEvngTcmJR/Nxun2g8fHDFqDOlTe8sdofFmEWbhh/UrlpQs8pFr27C2HYypy0CH9fn1gLB/Nsc0cd5MRUKui+LbKzQCbxtMncflAFKSVCfFbCaEGHCZbX2fUSRUZGKvdiZ10JTWA4ktu0SrLqSAVYP10bHqr1deYYwfeHzvFn0ckz5JTl22j9GlQnc5OJycGfnVOG1m1AWmM658=
